# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Padding (in pixels) around text for tabs.
# Type: Padding
c.tabs.padding = {'bottom': 3, 'left': 2, 'right': 2, 'top': 3}

# Alignment of the text inside of tabs.
# Type: TextAlignment
# Valid values:
#   - left
#   - right
#   - center
c.tabs.title.alignment = 'center'

# Width (in pixels or as percentage of the window) of the tab bar if
# it's vertical.
# Type: PercOrInt
c.tabs.width = '20%'

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
# Type: List of QtColor, or QtColor
c.colors.completion.fg = '#6c6c6c'

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = '#121212'

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = '#121212'

# Foreground color of completion widget category headers.
# Type: QtColor
c.colors.completion.category.fg = '#6c6c6c'

# Background color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.bg = '#121212'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.top = '#486348'

# Bottom border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.bottom = '#486348'

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = '#486348'

# Top border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.top = '#486348'

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = '#486348'

# Foreground color of the matched text in the selected completion item.
# Type: QtColor
c.colors.completion.item.selected.match.fg = '#683333'

# Foreground color of the matched text in the completion.
# Type: QtColor
c.colors.completion.match.fg = '#683333'

# Color of the scrollbar handle in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.fg = '#486348'

# Color of the scrollbar in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.bg = '#121212'

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = '#121212'

# Foreground color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.fg = '#6c6c6c'

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = '#121212'

# Background color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.bg = '#483368'

# Foreground color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.fg = '#6c6c6c'

# Default foreground color of the URL in the statusbar.
# Type: QssColor
c.colors.statusbar.url.fg = '#6c6c6c'

# Foreground color of the URL in the statusbar on error.
# Type: QssColor
c.colors.statusbar.url.error.fg = '#683333'

# Foreground color of the URL in the statusbar for hovered links.
# Type: QssColor
c.colors.statusbar.url.hover.fg = '#6c6c6c'

# Foreground color of the URL in the statusbar on successful load
# (http).
# Type: QssColor
c.colors.statusbar.url.success.http.fg = '#486348'

# Foreground color of the URL in the statusbar on successful load
# (https).
# Type: QssColor
c.colors.statusbar.url.success.https.fg = '#486348'

# Background color of the tab bar.
# Type: QssColor
c.colors.tabs.bar.bg = '#121212'

# Color gradient end for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.stop = '#486348'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#6c6c6c'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#121212'

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#6c6c6c'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#121212'

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#121212'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#486348'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#121212'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#486348'

# Background color of pinned unselected odd tabs.
# Type: QtColor
c.colors.tabs.pinned.odd.bg = '#121212'

# Background color of pinned unselected even tabs.
# Type: QtColor
c.colors.tabs.pinned.even.bg = '#121212'

# Foreground color of pinned selected odd tabs.
# Type: QtColor
c.colors.tabs.pinned.selected.odd.fg = '#486348'

# Background color of pinned selected odd tabs.
# Type: QtColor
c.colors.tabs.pinned.selected.odd.bg = '#121212'

# Background color of pinned selected even tabs.
# Type: QtColor
c.colors.tabs.pinned.selected.even.bg = '#121212'
